### ISSUE TITLE
Support dictionary of parameters

### ISSUE THREAD

**Issue by freddycct** [FluxML/Optimisers.jl#114]
### Describe the potential feature

`Optimisers.setup(Optimisers.Adam(), Dict(1 => rand(Float32, 5), 2=>rand(Float32, 5)))` currently returns empty tuple `()`

### Motivation

Would help more complicated neural architectures.

**Comment by ToucheSir** [comment]
We'd have to decide how/if to support Dicts in Functors first. Can you open an issue to this effect there?

**Comment by mcabbott** [comment]
Can you explain more about why or where `Dict` is a good idea, instead of say a `NamedTuple`? Is its mutability important? Are the keys things you invent, or is this something more like an `IdDict`?

**Comment by CarloLucibello** [comment]
Hi have a use case in 
https://github.com/CarloLucibello/GraphNeuralNetworks.jl/pull/146
where the keys are tuples of string, using named tuple instead would be awkward.
There could be some exotic situations where the dict's values are trained, although most of the time they contain static features. In any case though the have to be moved to gpus, so `functor` support is necessary.
