### ISSUE TITLE
Use `OptChain` as an alias for `OptimiserChain`?

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Optimisers.jl#138]
`OptimiserChain` is a bit too verbose,  with `OptChain` we go from 14 to 8 characters without losing clarity.

**Comment by mcabbott** [comment]
I had a branch somewhere to change the printing to `ClipNorm(1) => Descent(0.1)`, and also digest such strings of `=>`. 2 characters and no brackets.

**Comment by CarloLucibello** [comment]
Let's keep OptimiserChain as it is consolidated
