### ISSUE TITLE
AdamW: epsilon and lambda swapped?

### ISSUE THREAD

**Issue by murrellb** [FluxML/Optimisers.jl#197]
<img width="706" alt="image" src="https://github.com/user-attachments/assets/213648a2-aca9-4fa8-8f96-a0ee1a5cbff6">

Weird, given that the docs imply epsilon is non-zero:

<img width="508" alt="image" src="https://github.com/user-attachments/assets/5fdc1b98-d3b0-4470-a072-0ab395890a69">

But looking at the code, the field order in the struct vs the constructors seems to swap them?

<img width="706" alt="image" src="https://github.com/user-attachments/assets/c2e5b341-b94e-46cc-a473-0a659b750ce8">

**Comment by ToucheSir** [comment]
I think you may be right, but cc @CarloLucibello for another pair of eyes.

**Comment by CarloLucibello** [comment]
omg, that's a huge oversight. fix in #198
