### ISSUE TITLE
Package registration

### ISSUE THREAD

**Issue by oschulz** [FluxML/Optimisers.jl#20]
I'd love to use Optimizers for a package of mine, instead of depending on Flux as a whole - is there a timeline for registering it?

**Comment by DhairyaLGandhi** [comment]
I think we're good to merge with #19

**Comment by oschulz** [comment]
Thanks @DhairyaLGandhi !

**Comment by oschulz** [comment]
The idea is that this will replace the optimizer in Flux, right?

**Comment by ToucheSir** [comment]
Yup, that's correct.

**Comment by oschulz** [comment]
Don't mean to nag, is there a tentative date for a first release? Just asking because I have to schedule some work accordingly.

**Comment by DhairyaLGandhi** [comment]
Agreed that since we merged #19, let's get some folks on the new packages. Thanks! I'll set up the registrations.

**Comment by oschulz** [comment]
I'll close this, since registration is underway.
