### ISSUE TITLE
Correct the optimiser's eltype?

### ISSUE THREAD

**Issue by mcabbott** [FluxML/Optimisers.jl#55]
Should we add something to adjust the numbers in the optimiser to match the array? This hardly matters with Array etc, as both `update` and `update!` write back into an array of the same type. But with e.g. StaticArrays, a stray Float64 will promote the whole model. 

We could do something like this:
```julia
function retype(::Type{T}, opt::O) where {T,O}
  nt = map(n -> _retype(T, getfield(opt, n)), fieldnames(O)) 
  O.name.wrapper(nt...)
end
_retype(::Type{T}, p::AbstractFloat) where T = convert(T, p)
_retype(::Type{T}, t::Union{Tuple, NamedTuple}) where T = map(p -> _retype(T,p), t)
_retype(::Type, x) = x
```
This requires that the optimiser struct have a default constructor, and will only convert numbers and tuples. But if we add something like this now, it will be obvious from the beginning that your optimiser struct ought to work this way.

**Comment by ToucheSir** [comment]
Is this kind of adjustment something we always want to do? Perhaps a less intrusive option would be to convert the outputs of `apply` instead before patching. It'd be less efficient, but we wouldn't have to make any assumptions about how the optimisers work.

**Comment by mcabbott** [comment]
That's probably a better idea. We can make `subtract!(Float16[1,2,3], Float64[4,5,6])` always return the first eltype, even for immutable arrays.
