### ISSUE TITLE
doc improvement: working with custom model types

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Optimisers.jl#84]
We should give more prominence in the docs to the usage of `Flux.@functor` and `Optimisers.trainable` to define trainable parameters of custom types.

**Comment by mcabbott** [comment]
Yes. Where's the best place? 

I don't want every docstring to become a novel, but perhaps the one for `Optimisers.setup` is one good place to show that this recurses into custom structs.

The main doc page uses a Flux model as the first example of applying a rule. It could instead first construct some simpler model, and show that a newly written optimisation rule is applied to all children etc?

**Comment by CarloLucibello** [comment]
this seems done
