### ISSUE TITLE
support a nice way of changing the learning rate

### ISSUE THREAD

**Issue by SobhanMP** [FluxML/Optimisers.jl#88]
It would be nice to have a easy and rule independent way of changing the learning rate like in Flux.jl.  

Right now the best way i can think of is making another state tuple while changing the first argument but then changing the learning rate is not rule independent.

@mcabbott  suggested
> Although perhaps there ought to be one, like `st = setup(rule, st)` without zero-ing the momenta. Maybe make an issue?

related: #15 (seems to be not active)

**Comment by mcabbott** [comment]
See what you think of #89. I made it a new verb, although perhaps it could in fact be made a method of `setup` --- the signature of the first call doesn't really distinguish the two uses, but the state tree contains `Leaf` or `nothing`, and never contains new parameters (i.e. things with `isnumeric(x)`).

**Comment by SobhanMP** [comment]
looks pretty good.
