### ISSUE TITLE
"Optimisers.jl does not at present handle tied weights, sorry."

### ISSUE THREAD

**Issue by gdalle** [FluxML/Optimisers.jl#97]
Hi, and thanks for the hard work on Flux!
Do we have an idea what is causing this error?

**Comment by mcabbott** [comment]
One way is #42, which you can try via `] add https://github.com/mcabbott/Optimisers.jl#duplicated` -- would be interesting to see whether it works well in the wild. 

Brian had an idea for a less complicated implementation, so #42 may or may not actually get merged.

**Comment by darsnack** [comment]
> Do we have an idea what is causing this error?

In case this was a question for clarity on what the error means: you have a model where two parameters share the same underlying array (e.g. auto-encoders). We currently don't have a good way of accumulating the gradients in all these cases reliably. So, we error instead.

**Comment by gdalle** [comment]
Thanks for the answers! I actually understood the error message, but since tied weights obviously work in Flux.jl itself, I was simply wondering why it didn't for this library.
In my case, the error was generated by a `ReshapeLayer` from Lux.jl, which is pretty annoying for such a simple block. But as always, the solution is way more complicated to implement than the problem is to state.

**Comment by ToucheSir** [comment]
`ReshapeLayer` should not be causing an error like this since it reshapes an output on the fly (vs a parameter offline, which is what this is supposed to catch). Do you have a MWE for that?

**Comment by ToucheSir** [comment]
May be https://github.com/avik-pal/Lux.jl/pull/74, I remember something similar from the issue which spawned that.

**Comment by ToucheSir** [comment]
And see #100 for the aforementioned alternate spin on handling tied weights.
